Thu Aug 14 11:42:47 EDT 2025
+--------------------------------------------------------------------------------------+
|              [31mHome[0m Usage for user [31mycao73[0m as of [31mThu Aug 14 11:00:10 2025[0m               |
+----------------------+----------------------+-------------------+--------------------+
|         Used         |        Quota         |      Percent      |       Files        |
+----------------------+----------------------+-------------------+--------------------+
|       44.20 GB       |       50.00 GB       |       88.41%      |      596,976       |
+----------------------+----------------------+-------------------+--------------------+

+------------------------------------------------------------------------------------------+
|              [31mGPFS[0m Usage for Group [31mpclancy3:[0m as of [31mThu Aug 14 11:30:14 2025[0m               |
+------------+-----------+-----------+---------+------------+---------------+--------------+
|     FS     |    Used   |   Quota   |  Used % |   Files    |  Files Quota  |   Files %    |
+------------+-----------+-----------+---------+------------+---------------+--------------+
|    data    |  9.04 TB  |  10.00 TB |  90.00% |  406,491   |   4,096,000   |    9.00%     |
|  scratch4  |  9.30 TB  |  10.00 TB |  93.00% | 1,478,080  |   5,242,880   |    28.00%    |
| scratch16  |  17.23 TB |  20.00 TB |  86.00% | 1,434,153  |   20,480,000  |    7.00%     |
+------------+-----------+-----------+---------+------------+---------------+--------------+

Consider completing our user survey to provide feedback to help improve the cluster: https://jh.qualtrics.com/jfe/form/SV_bQOKO9M7xQFmwAu

Currently Loaded Modules:
  1) gcc/9.3.0       3) slurm/19.05.7   5) lua/5.4.4       7) git/2.28.0
  2) openmpi/3.1.6   4) lmod/8.7.24     6) helpers/0.1.1   8) standard/2020.10
Running mace_md_eval0814.py
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
WARNING:root:'model_path' argument is deprecated, please use 'model_paths' in the future.
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/calculators/mace.py:139: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  torch.load(f=model_path, map_location=device)
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py:1488: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn(
cuequivariance or cuequivariance_torch is not available. Cuequivariance acceleration will be disabled.
Loaded structure from ../2L_octo_Cr2_v2_relax.extxyz
Supercell dimensions: 5x5x1
Total atoms: 2050
Traceback (most recent call last):
  File "/data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/4.lmp/Rippling/2L_octo_Cr2_v2/0806/2-naive-fine-tuning/mace_md_eval0814.py", line 343, in <module>
    csv_files = run_mace_md(input_file, nx=nx, ny=ny, nz=nz,
  File "/data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/4.lmp/Rippling/2L_octo_Cr2_v2/0806/2-naive-fine-tuning/mace_md_eval0814.py", line 73, in run_mace_md
    calculator = MACECalculator(model_path=model_paths, device=device)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/calculators/mace.py", line 138, in __init__
    self.models = [
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/calculators/mace.py", line 139, in <listcomp>
    torch.load(f=model_path, map_location=device)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 1500, in load
    return torch.jit.load(opened_file, map_location=map_location)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/jit/_serialization.py", line 162, in load
    map_location = validate_map_location(map_location)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/jit/_serialization.py", line 192, in validate_map_location
    validate_cuda_device(map_location)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 625, in validate_cuda_device
    return _validate_device(location, "cuda").index
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 605, in _validate_device
    raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Running mace_md_eval0814.py done
Thu Aug 14 11:43:03 EDT 2025
